version: '3'
services:
  user-service:
    build:
      context: ./user-service
    image: tlrruddbs/user-service:1.0
    ports:
      - "1001:1001"
    networks:
      - spring-network
    depends_on:
      - order-service

  order-service:
    build:
      context: ./order-service
    image: tlrruddbs/order-service:1.0
    ports:
      - "1002:1002"
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
